### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [voghDev/ChuckNorrisJokes#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by voghDev** [comment]
Hi Oleksiy,

I've already heard about MockK and it sounds great. Thanks for this awesome job.

I'm planning to have a look at other mocking choices for future projects. MockK is definitely one of them. I'll let you know about the progress and ask you any doubt I might have. Thanks for your help
